"""HTML email templates for stock analysis reports.

Localized to English (en) and Simplified Chinese (zh). Language is taken
from result["language"] which the orchestrator detects from the user query.
"""

import html
from datetime import datetime


# All static label strings used in email templates, keyed by language code.
LABELS = {
    "en": {
        "subject_prefix": "[Stock Analysis]",
        "subject_confidence": "confidence",
        "watchlist_subject": "[Stock Watchlist] Daily Analysis Summary",
        "report_title": "Stock Analysis Report",
        "watchlist_title": "Daily Stock Watchlist Summary",
        "generated": "Generated",
        "confidence": "Confidence",
        "horizon": "Horizon",
        "key_metrics": "Key Metrics",
        "price": "Price",
        "pe_ratio": "P/E Ratio",
        "rsi": "RSI(14)",
        "range_52w": "52W Range",
        "sentiment": "Sentiment",
        "fund_health": "Fundamental Health",
        "quant_score": "Quant Score",
        "risk": "Risk",
        "reasoning": "Reasoning",
        "supporting_factors": "Supporting Factors",
        "dissenting_factors": "Dissenting Factors",
        "debate": "Bull vs Bear Debate",
        "no_debate": "No debate available.",
        "round": "Round",
        "grid_strategies": "Grid Trading Strategies",
        "grid_suitability": "Suitability",
        "grid_volatility": "Annual Volatility",
        "grid_best": "Best Strategy",
        "grid_per_month": "/month",
        "table_strategy": "Strategy",
        "table_range": "Range",
        "table_grids": "Grids",
        "table_shares": "Shares",
        "table_profit": "Profit/Cycle",
        "table_monthly": "Est. Monthly",
        "risk_factors": "Risk Factors",
        "disclaimer_label": "Disclaimer",
        "footer": "Generated by Multi-Agent Investment Research System (LangGraph + DeepSeek)",
        "table_ticker": "Ticker",
        "table_change": "Change",
        "table_action": "Action",
        "table_quant": "Quant",
        "table_risk": "Risk",
        "default_disclaimer": "For educational purposes only. Not financial advice.",
    },
    "zh": {
        "subject_prefix": "【股票分析】",
        "subject_confidence": "置信度",
        "watchlist_subject": "【股票观察列表】每日分析汇总",
        "report_title": "股票分析报告",
        "watchlist_title": "每日股票观察列表汇总",
        "generated": "生成时间",
        "confidence": "置信度",
        "horizon": "投资周期",
        "key_metrics": "核心指标",
        "price": "价格",
        "pe_ratio": "市盈率",
        "rsi": "RSI(14)",
        "range_52w": "52周区间",
        "sentiment": "情绪",
        "fund_health": "基本面健康度",
        "quant_score": "量化评分",
        "risk": "风险",
        "reasoning": "推理逻辑",
        "supporting_factors": "支持因素",
        "dissenting_factors": "反对因素",
        "debate": "多空辩论",
        "no_debate": "暂无辩论数据。",
        "round": "第",
        "grid_strategies": "网格交易策略",
        "grid_suitability": "适合度",
        "grid_volatility": "年化波动率",
        "grid_best": "最佳策略",
        "grid_per_month": "/月",
        "table_strategy": "策略",
        "table_range": "区间",
        "table_grids": "网格数",
        "table_shares": "股数/格",
        "table_profit": "单次利润",
        "table_monthly": "预估月收益",
        "risk_factors": "风险因素",
        "disclaimer_label": "免责声明",
        "footer": "由 Multi-Agent Investment Research System（LangGraph + DeepSeek）生成",
        "table_ticker": "代码",
        "table_change": "涨跌",
        "table_action": "建议",
        "table_quant": "量化",
        "table_risk": "风险",
        "default_disclaimer": "仅供教育和参考目的，不构成投资建议。",
    },
}


def _labels(language: str) -> dict:
    return LABELS.get(language, LABELS["en"])


def _esc(value) -> str:
    """Escape HTML."""
    return html.escape(str(value)) if value is not None else "N/A"


def _color_for_recommendation(rec: str) -> str:
    return {
        "buy": "#16a34a",
        "sell": "#dc2626",
        "hold": "#ea580c",
    }.get(rec.lower(), "#6b7280")


def _color_for_score(score: float, max_val: float = 100, reverse: bool = False) -> str:
    """Green for good, red for bad. reverse=True for risk scores."""
    if score is None:
        return "#6b7280"
    pct = score / max_val
    if reverse:
        pct = 1 - pct
    if pct >= 0.7:
        return "#16a34a"
    elif pct >= 0.4:
        return "#ea580c"
    else:
        return "#dc2626"


def render_analysis_email(result: dict) -> tuple[str, str, str]:
    """
    Render a single stock analysis result into HTML email content.

    Returns:
        (subject, html_body, text_body)
    """
    ticker = result.get("ticker", "?")
    rec_obj = result.get("recommendation", {})
    rec = rec_obj.get("recommendation", "N/A")
    confidence = rec_obj.get("confidence", 0)
    horizon = rec_obj.get("investment_horizon", "N/A")
    language = result.get("language", "en")
    L = _labels(language)

    md = result.get("market_data", {})
    sentiment = result.get("sentiment", {})
    fundamental = result.get("fundamental", {})
    quant = result.get("quant", {})
    grid = result.get("grid_strategy", {})
    risk = result.get("risk", {})
    debate_history = result.get("debate_history", [])

    subject = f"{L['subject_prefix']} {ticker} - {rec.upper()} ({confidence:.0%} {L['subject_confidence']})"

    rec_color = _color_for_recommendation(rec)

    html_body = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{_esc(subject)}</title></head>
<body style="font-family: -apple-system, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #1f2937; background: #f9fafb;">

<div style="background: white; padding: 30px; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">

<h1 style="margin: 0 0 5px 0; color: #111827;">{L['report_title']}</h1>
<p style="color: #6b7280; margin: 0 0 25px 0;">{L['generated']} {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>

<!-- Header card -->
<div style="background: linear-gradient(135deg, #f3f4f6 0%, #e5e7eb 100%); padding: 25px; border-radius: 8px; margin-bottom: 25px;">
  <h2 style="margin: 0 0 10px 0; color: #111827; font-size: 32px;">{_esc(ticker)}</h2>
  <div style="font-size: 28px; font-weight: bold; color: {rec_color};">{_esc(rec.upper())}</div>
  <div style="color: #4b5563; margin-top: 5px;">{L['confidence']}: {confidence:.0%} | {L['horizon']}: {_esc(horizon)}</div>
</div>

<!-- Key metrics -->
<h3 style="color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">{L['key_metrics']}</h3>
<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
  <tr>
    <td style="padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb;"><strong>{L['price']}</strong></td>
    <td style="padding: 10px; border: 1px solid #e5e7eb;">${_esc(md.get('current_price'))} ({_esc(md.get('price_change_pct'))}%)</td>
  </tr>
  <tr>
    <td style="padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb;"><strong>{L['pe_ratio']}</strong></td>
    <td style="padding: 10px; border: 1px solid #e5e7eb;">{_esc(md.get('pe_ratio'))}</td>
  </tr>
  <tr>
    <td style="padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb;"><strong>{L['rsi']}</strong></td>
    <td style="padding: 10px; border: 1px solid #e5e7eb;">{_esc(md.get('rsi_14'))}</td>
  </tr>
  <tr>
    <td style="padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb;"><strong>{L['range_52w']}</strong></td>
    <td style="padding: 10px; border: 1px solid #e5e7eb;">{_esc(md.get('fifty_two_week_low'))} - {_esc(md.get('fifty_two_week_high'))}</td>
  </tr>
  <tr>
    <td style="padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb;"><strong>{L['sentiment']}</strong></td>
    <td style="padding: 10px; border: 1px solid #e5e7eb;">{_esc(sentiment.get('overall_label'))} ({_esc(sentiment.get('overall_score'))})</td>
  </tr>
  <tr>
    <td style="padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb;"><strong>{L['fund_health']}</strong></td>
    <td style="padding: 10px; border: 1px solid #e5e7eb;"><span style="color: {_color_for_score(fundamental.get('health_score'), 10)};">{_esc(fundamental.get('health_score'))}/10</span></td>
  </tr>
  <tr>
    <td style="padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb;"><strong>{L['quant_score']}</strong></td>
    <td style="padding: 10px; border: 1px solid #e5e7eb;">{_esc(quant.get('score'))}/100 ({_esc(quant.get('verdict'))})</td>
  </tr>
  <tr>
    <td style="padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb;"><strong>{L['risk']}</strong></td>
    <td style="padding: 10px; border: 1px solid #e5e7eb;"><span style="color: {_color_for_score(risk.get('risk_score'), 10, reverse=True)};">{_esc(risk.get('risk_score'))}/10 ({_esc(risk.get('risk_level'))})</span></td>
  </tr>
</table>

<!-- Recommendation reasoning -->
<h3 style="color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">{L['reasoning']}</h3>
<p style="line-height: 1.6;">{_esc(rec_obj.get('reasoning'))}</p>

<!-- Supporting / dissenting -->
<table style="width: 100%; margin-bottom: 20px;">
  <tr>
    <td style="vertical-align: top; padding-right: 10px; width: 50%;">
      <h4 style="color: #16a34a;">{L['supporting_factors']}</h4>
      <ul>{"".join(f"<li>{_esc(f)}</li>" for f in rec_obj.get('supporting_factors', []))}</ul>
    </td>
    <td style="vertical-align: top; padding-left: 10px; width: 50%;">
      <h4 style="color: #dc2626;">{L['dissenting_factors']}</h4>
      <ul>{"".join(f"<li>{_esc(f)}</li>" for f in rec_obj.get('dissenting_factors', []))}</ul>
    </td>
  </tr>
</table>

<!-- Bull vs Bear debate -->
<h3 style="color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">{L['debate']}</h3>
{_render_debate(debate_history, L)}

<!-- Grid Strategy -->
{_render_grid(grid, L)}

<!-- Risk factors -->
<h3 style="color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">{L['risk_factors']}</h3>
<ul>{"".join(f"<li>{_esc(f)}</li>" for f in risk.get('risk_factors', []))}</ul>

<!-- Disclaimer -->
<div style="margin-top: 30px; padding: 15px; background: #fef3c7; border-left: 4px solid #f59e0b; border-radius: 4px; font-size: 13px; color: #78350f;">
  <strong>{L['disclaimer_label']}:</strong> {_esc(rec_obj.get('disclaimer', L['default_disclaimer']))}
</div>

</div>

<p style="text-align: center; color: #9ca3af; font-size: 12px; margin-top: 20px;">
  {L['footer']}
</p>

</body>
</html>"""

    text_body = (
        f"{L['report_title']}: {ticker}\n"
        f"{'=' * 50}\n"
        f"{L['table_action']}: {rec.upper()} ({L['confidence']}: {confidence:.0%}, {L['horizon']}: {horizon})\n\n"
        f"{L['price']}: ${md.get('current_price')} ({md.get('price_change_pct')}%)\n"
        f"{L['pe_ratio']}: {md.get('pe_ratio')} | {L['rsi']}: {md.get('rsi_14')}\n"
        f"{L['sentiment']}: {sentiment.get('overall_label')} ({sentiment.get('overall_score')})\n"
        f"{L['fund_health']}: {fundamental.get('health_score')}/10\n"
        f"{L['quant_score']}: {quant.get('score')}/100 ({quant.get('verdict')})\n"
        f"{L['risk']}: {risk.get('risk_score')}/10 ({risk.get('risk_level')})\n\n"
        f"{L['reasoning']}: {rec_obj.get('reasoning', 'N/A')}\n\n"
        f"{L['disclaimer_label']}: {rec_obj.get('disclaimer', L['default_disclaimer'])}\n"
    )

    return subject, html_body, text_body


def _render_debate(history: list[dict], L: dict) -> str:
    if not history:
        return f"<p>{L['no_debate']}</p>"
    out = ""
    for entry in history:
        role = entry.get("role", "?").upper()
        rnd = entry.get("round_number", "?")
        color = "#16a34a" if role == "BULL" else "#dc2626"
        out += f"""
        <div style="background: #f9fafb; padding: 15px; border-left: 4px solid {color}; margin-bottom: 10px; border-radius: 4px;">
          <div style="font-weight: bold; color: {color}; margin-bottom: 5px;">{role} - {L['round']} {rnd}</div>
          <p style="margin: 0 0 8px 0;">{_esc(entry.get('argument', ''))}</p>
          <ul style="margin: 5px 0; padding-left: 20px;">
            {"".join(f"<li>{_esc(p)}</li>" for p in entry.get('key_points', []))}
          </ul>
        </div>
        """
    return out


def _render_grid(grid: dict, L: dict) -> str:
    if not grid or not grid.get("strategies"):
        return ""
    score = grid.get("score", 0)
    verdict = grid.get("verdict", "N/A")
    color = "#16a34a" if score >= 70 else "#ea580c" if score >= 50 else "#dc2626"

    out = f"""
    <h3 style="color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">{L['grid_strategies']}</h3>
    <p>{L['grid_suitability']}: <span style="color: {color}; font-weight: bold;">{score}/100 ({verdict})</span> |
       {L['grid_volatility']}: {grid.get('annual_volatility_pct', 0)}%</p>
    <p><strong>{L['grid_best']}:</strong> {_esc(grid.get('best_strategy_name', 'none'))}
       (~{grid.get('best_monthly_return_pct', 0)}%{L['grid_per_month']})</p>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 15px;">
      <tr style="background: #f3f4f6;">
        <th style="padding: 8px; border: 1px solid #e5e7eb; text-align: left;">{L['table_strategy']}</th>
        <th style="padding: 8px; border: 1px solid #e5e7eb; text-align: left;">{L['table_range']}</th>
        <th style="padding: 8px; border: 1px solid #e5e7eb; text-align: right;">{L['table_grids']}</th>
        <th style="padding: 8px; border: 1px solid #e5e7eb; text-align: right;">{L['table_shares']}</th>
        <th style="padding: 8px; border: 1px solid #e5e7eb; text-align: right;">{L['table_profit']}</th>
        <th style="padding: 8px; border: 1px solid #e5e7eb; text-align: right;">{L['table_monthly']}</th>
      </tr>
    """
    for s in grid["strategies"]:
        out += f"""
        <tr>
          <td style="padding: 8px; border: 1px solid #e5e7eb;">{_esc(s['name'])}<br><small style="color: #6b7280;">{_esc(s['horizon'])}</small></td>
          <td style="padding: 8px; border: 1px solid #e5e7eb;">{s['lower_price']} - {s['upper_price']}</td>
          <td style="padding: 8px; border: 1px solid #e5e7eb; text-align: right;">{s['grid_count']}</td>
          <td style="padding: 8px; border: 1px solid #e5e7eb; text-align: right;">{s['shares_per_grid']}</td>
          <td style="padding: 8px; border: 1px solid #e5e7eb; text-align: right;">{s['profit_per_cycle']} CNY</td>
          <td style="padding: 8px; border: 1px solid #e5e7eb; text-align: right;">{s['estimated_monthly_return_pct']}%</td>
        </tr>
        """
    out += "</table>"
    return out


def render_batch_summary(results: list[dict]) -> tuple[str, str, str]:
    """
    Render a batch summary email when analyzing multiple stocks.

    Language is taken from the FIRST result's language field. If a watchlist
    contains mixed languages, the subject and headers use the first one.

    Returns:
        (subject, html_body, text_body)
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    language = results[0].get("language", "en") if results else "en"
    L = _labels(language)
    subject = f"{L['watchlist_subject']} - {timestamp}"

    rows = ""
    text_lines = [f"{L['watchlist_title']} - {timestamp}", "=" * 60]
    for result in results:
        ticker = result.get("ticker", "?")
        rec = result.get("recommendation", {}).get("recommendation", "N/A")
        conf = result.get("recommendation", {}).get("confidence", 0)
        price = result.get("market_data", {}).get("current_price", "N/A")
        change = result.get("market_data", {}).get("price_change_pct", 0)
        risk_score = result.get("risk", {}).get("risk_score", "N/A")
        quant_score = result.get("quant", {}).get("score", "N/A")

        color = _color_for_recommendation(rec)
        rows += f"""
        <tr>
          <td style="padding: 10px; border: 1px solid #e5e7eb;"><strong>{_esc(ticker)}</strong></td>
          <td style="padding: 10px; border: 1px solid #e5e7eb;">${_esc(price)}</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb;">{_esc(change)}%</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb;"><span style="color: {color}; font-weight: bold;">{_esc(rec.upper())}</span></td>
          <td style="padding: 10px; border: 1px solid #e5e7eb;">{conf:.0%}</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb;">{_esc(quant_score)}/100</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb;">{_esc(risk_score)}/10</td>
        </tr>
        """
        text_lines.append(
            f"  {ticker:12} ${price:>10} ({change:+.2f}%)  {rec.upper():4} {conf:.0%}  Quant:{quant_score}  Risk:{risk_score}"
        )

    html_body = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; color: #1f2937;">
<h1>{L['watchlist_title']}</h1>
<p style="color: #6b7280;">{L['generated']} {timestamp}</p>
<table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
  <tr style="background: #f3f4f6;">
    <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left;">{L['table_ticker']}</th>
    <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left;">{L['price']}</th>
    <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left;">{L['table_change']}</th>
    <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left;">{L['table_action']}</th>
    <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left;">{L['confidence']}</th>
    <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left;">{L['table_quant']}</th>
    <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left;">{L['table_risk']}</th>
  </tr>
  {rows}
</table>
<p style="margin-top: 30px; padding: 15px; background: #fef3c7; border-left: 4px solid #f59e0b; font-size: 13px; color: #78350f;">
  <strong>{L['disclaimer_label']}:</strong> {L['default_disclaimer']}
</p>
</body></html>"""

    text_body = "\n".join(text_lines)
    return subject, html_body, text_body
